apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-googlechat
  labels:
    app: synapse-googlechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse-googlechat
  template:
    metadata:
      labels:
        app: synapse-googlechat
    spec:
      hostname: synapse-googlechat
      subdomain: pausalenovo
      containers:
      - name: synapse-googlechat
        image: dock.mau.dev/mautrix/googlechat:latest
        ports:
        - containerPort: 29317
        env:
        - name: UID
          value: "1000"
        - name: GID
          value: "1000"
        volumeMounts:
        - name: config
          mountPath: /data
        - name: localtime
          mountPath: /etc/localtime
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
      - name: config
        hostPath:
          path: /home/pausa/.config/synapse-googlechat
          type: DirectoryOrCreate
          # TODO liveness probe
