apiVersion: v1
kind: Service
metadata:
  name: samba
spec:
  selector:
    app: samba
  type: NodePort
  ports:
  - name: smb1
    protocol: TCP
    port: 139
    nodePort: 139
  - name: smb2
    protocol: TCP
    port: 445
    nodePort: 445
