apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
  labels:
    app: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      labels:
        app: synapse
    spec:
      hostname: synapse
      subdomain: pausalenovo
      containers:
      - name: synapse
        image: matrixdotorg/synapse:latest
        ports:
        - containerPort: 8008
        env:
        - name: UID
          value: "1000"
        - name: GID
          value: "1001"
        volumeMounts:
        - name: config
          mountPath: /data
        - name: localtime
          mountPath: /etc/localtime
        livenessProbe:
          httpGet:
            path: /_matrix/client/versions
            port: 8008
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
      - name: config
        hostPath:
          path: /home/pausa/.config/synapse
          type: DirectoryOrCreate
      - name: certs
        hostPath: 
          path: /home/pausa/Private
          type: Directory
