apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser
  labels:
    app: browser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browser
  template:
    metadata:
      labels:
        app: browser
    spec:
      hostname: browser
      subdomain: pausalenovo
      containers:
      - name: browser
        image: filebrowser/filebrowser:latest
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - name: media
          mountPath: /srv
        - name: localtime
          mountPath: /etc/localtime
        - name: db
          mountPath: /database.db
        - name: config
          mountPath: /.filebrowser.json
          subPath: .filebrowser.json
      volumes:
      - name: media
        hostPath: 
          path: /home/pausa/media
          type: DirectoryOrCreate
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
      - name: db
        hostPath:
          path: /home/pausa/.config/browser/database.db
          type: FileOrCreate
      - name: config
        configMap: 
          name: browser
          items:
          - key: browser.json
            path: .filebrowser.json
        
