apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  labels:
    app: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      hostname: caddy
      subdomain: pausalenovo
      containers:
      - name: caddy
        image: pausa-caddy:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 443
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: data
          mountPath: /data
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
      - name: data
        hostPath: 
          path: /home/pausa/.config/caddy
          type: Directory
          
