apiVersion: v1
kind: Service
metadata:
  name: caddy
spec:
  selector:
    app: caddy
  type: NodePort
  ports:
  - name: http2
    protocol: TCP
    port: 443
    nodePort: 443
  - name: http
    protocol: TCP
    port: 80
    nodePort: 80
  - name: synapse
    protocol: TCP
    port: 8448
    nodePort: 8448
  - name: lan
    protocol: TCP
    port: 8886
    nodePort: 8886
