apiVersion: v1
kind: Service
metadata:
  name: dns
spec:
  selector:
    app: dns
  type: NodePort
  ports:
  - name: http
    protocol: UDP
    port: 53
    nodePort: 53
  - name: http2
    protocol: TCP
    port: 53
    nodePort: 53
