apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx
  labels:
    app: influx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influx
  template:
    metadata:
      labels:
        app: influx
    spec:
      hostname: influx
      subdomain: pausalenovo
      containers:
      - name: influx
        image: influxdb:2.7
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: data
          mountPath: /var/lib/influxdb2
        - name: passwd
          mountPath: /etc/passwd
          readOnly: true
        - name: localtime
          mountPath: /etc/localtime
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
      - name: data
        hostPath:
          path: /home/pausa/media/db/influx
          type: DirectoryOrCreate
      - name: passwd
        hostPath:
          path: /etc/passwd
          type: File
          # TODO liveness probe
