apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostname: plex
      subdomain: pausalenovo
      containers:
      - name: plex
        image: linuxserver/plex:latest
        ports:
        - containerPort: 32400
        - containerPort: 3005
        - containerPort: 8324
        - containerPort: 32469
        - containerPort: 1900
        - containerPort: 32410
        - containerPort: 32412
        - containerPort: 32413
        - containerPort: 32414
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: VERSION
          value: docker
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
        - name: localtime
          mountPath: /etc/localtime
      volumes:
      - name: config
        hostPath: 
          path: /home/pausa/.config/plex
          type: DirectoryOrCreate
      - name: media
        hostPath: 
          path: /home/pausa/media/
          type: DirectoryOrCreate
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
