
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
discovery:
remote:
  - platform: harmony
    name: Harmony Hub
    host: 192.168.178.220
media_player:
  - platform: plex
tplink:
  discovery: false
  switch:
  - host: 192.168.178.151 # salotto
  - host: 192.168.178.199 # gufo
