apiVersion: v1
kind: Service
metadata:
  name: aria2
spec:
  selector:
    app: aria2
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 6800
    nodePort: 6800
  - name: torrent-tcp
    protocol: TCP
    port: 6801
    nodePort: 6801
  - name: torrent-udp
    protocol: UDP
    port: 6801
    nodePort: 6801
