apiVersion: v1
kind: Service
metadata:
  name: calibre
spec:
  selector:
    app: calibre
  type: NodePort
  ports:
  - name: web
    protocol: TCP
    port: 8081
    nodePort: 28081
  - name: guac
    protocol: TCP
    port: 8080
    nodePort: 28080
  - name: conn
    protocol: TCP
    port: 9090
    nodePort: 29090
