apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-whatsapp
  labels:
    app: synapse-whatsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse-whatsapp
  template:
    metadata:
      labels:
        app: synapse-whatsapp
    spec:
      hostname: synapse-whatsapp
      subdomain: pausalenovo
      initContainers:
        - name: initbusybox
          image: busybox
          securityContext:
            privileged: true
          command:
          - sysctl
          - -w
          - net.ipv6.conf.all.disable_ipv6=1
      containers:
      - name: synapse-whatsapp
        image: dock.mau.dev/mautrix/whatsapp:v26.01
        ports:
        - containerPort: 29317
        env:
        - name: UID
          value: "1000"
        - name: GID
          value: "1000"
        volumeMounts:
        - name: config
          mountPath: /data
        - name: localtime
          mountPath: /etc/localtime
        - name: passwd
          mountPath: /etc/passwd
          readOnly: true
        livenessProbe:
          tcpSocket:
            port: 29317
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
      - name: config
        hostPath:
          path: /home/pausa/.config/synapse-whatsapp
          type: DirectoryOrCreate
      - name: passwd
        hostPath:
          path: /etc/passwd
          type: File

