apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
  labels:
    app: deluge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  template:
    metadata:
      labels:
        app: deluge
    spec:
      hostname: deluge
      subdomain: pausalenovo
      containers:
      - name: deluge
        image: linuxserver/deluge:latest
        ports:
        - containerPort: 8112
        - containerPort: 58846
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
        - name: media
          mountPath: /media
        - name: localtime
          mountPath: /etc/localtime
      volumes:
      - name: config
        hostPath: 
          path: /home/pausa/.config/deluge
          type: DirectoryOrCreate
      - name: downloads
        hostPath: 
          path: /home/pausa/media/private
          type: DirectoryOrCreate
      - name: media
        hostPath: 
          path: /home/pausa/media
          type: DirectoryOrCreate
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
