apiVersion: v1
kind: Service
metadata:
  name: deluge
spec:
  selector:
    app: deluge
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8112
    nodePort: 8112
  - name: client
    protocol: TCP
    port: 58846
    nodePort: 58846
