apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      hostname: jellyfin
      subdomain: pausalenovo
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:latest
        ports:
        - containerPort: 8096
        - containerPort: 7359
        env:
        - name: JELLYFIN_PublishedServerUrl
          value: "https://plex.pausa.dev"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: config
        hostPath: 
          path: /home/pausa/.config/jellyfin
          type: DirectoryOrCreate
      - name: media
        hostPath: 
          path: /home/pausa/media/
          type: DirectoryOrCreate
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
