apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  selector:
    app: jellyfin
  type: NodePort
  ports:
  - name: jellyfin-tcp
    protocol: TCP
    port: 8096
    nodePort: 8096
  - name: jellyfin-udp
    protocol: UDP
    port: 7359
    nodePort: 7359
