apiVersion: apps/v1
kind: Deployment
metadata:
  name: rutorrent
  labels:
    app: rutorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rutorrent
  template:
    metadata:
      labels:
        app: rutorrent
    spec:
      hostname: rutorrent
      subdomain: pausalenovo
      serviceAccountName: vpn
      dnsConfig:
        nameservers:
          - 103.86.96.100
          - 103.86.99.100
      containers:
      - name: rutorrent
        image: localhost:32000/rutorrent-flood:latest
        stdin: true
        tty: true
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        ports:
        - containerPort: 443
        - containerPort: 3000
        - containerPort: 51415
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
        - name: media
          mountPath: /host-media
        - name: localtime
          mountPath: /etc/localtime
        - name: tun
          mountPath: /dev/net/tun
      volumes:
      - name: config
        hostPath: 
          path: /home/pausa/.config/rutorrent
          type: DirectoryOrCreate
      - name: downloads
        hostPath: 
          path: /home/pausa/media/private
          type: DirectoryOrCreate
      - name: media
        hostPath: 
          path: /home/pausa/media
          type: DirectoryOrCreate
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
      - name: tun	
        hostPath:	
          path: /dev/net/tun	
          type: CharDevice
