apiVersion: v1
kind: Service
metadata:
  name: syncthing
spec:
  selector:
    app: syncthing
  type: NodePort
  ports:
  - name: web
    protocol: TCP
    port: 8384
    nodePort: 8384
  - name: tcp-transfer
    protocol: TCP
    port: 22000
    nodePort: 22000
  - name: udp-transfer
    protocol: UDP
    port: 22000
    nodePort: 22000
  - name: discovery
    protocol: UDP
    port: 21027
    nodePort: 21027
