apiVersion: apps/v1
kind: Deployment
metadata:
  name: tandoor
  labels:
    app: tandoor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tandoor
  template:
    metadata:
      labels:
        app: tandoor
    spec:
      enableServiceLinks: False
      hostname: tandoor
      subdomain: pausalenovo
      securityContext:
        fsGroup: 1000
      containers:
      - name: tandoor
        image: vabene1111/recipes:1.5.24
        ports:
        - containerPort: 8080
        env:
        - name: UID
          value: "1000"
        - name: GID
          value: "1001"
        - name: DB_ENGINE
          value: "django.db.backends.sqlite3"
        - name: POSTGRES_DB
          value: "/opt/recipes/db/databse.db"
        - name: CSRF_TRUSTED_ORIGINS
          value: "https://madpausa.sytes.net:54000"
        envFrom:
        - secretRef:
            name: tandoor
        volumeMounts:
        - name: media
          mountPath: /opt/recipes/mediafiles
        - name: static
          mountPath: /opt/recipes/staticfiles
        - name: db
          mountPath: /opt/recipes/db
        - name: localtime
          mountPath: /etc/localtime
      - name: tandoor-tls
        image: localhost:32000/tandoor-tls
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: certs
          mountPath: /certs
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
      - name: media
        hostPath:
          path: /home/pausa/.config/tandoor/mediafiles
          type: Directory
      - name: db
        hostPath:
          path: /home/pausa/.config/tandoor/db
          type: Directory
      - name: static
        hostPath:
          path: /home/pausa/.config/tandoor/staticfiles
          type: Directory
      - name: certs
        hostPath: 
          path: /home/pausa/Private
          type: Directory
