apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backupper
  labels:
    app: backupper
spec:
  schedule: 0 0 * * *
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          hostname: backupper
          subdomain: pausalenovo
          restartPolicy: Never
          containers:
          - name: backupper
            image: localhost:32000/backupper
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
            volumeMounts:
            - name: src-git-repo
              mountPath: /src/git-repo
            - name: src-castle
              mountPath: /src/castle
            - name: src-criminal
              mountPath: /src/criminal
            - name: src-ranma
              mountPath: /src/ranma
            - name: src-sync
              mountPath: /src/sync
            - name: src-db
              mountPath: /src/db
            - name: src-dot-config
              mountPath: /src/dot-config
            - name: dst
              mountPath: /dst
            - name: localtime
              mountPath: /etc/localtime
            env:
            - name: SRC
              value: /src
            - name: DST
              value: /dst/backup
          volumes:
          - name: src-git-repo
            hostPath:
              path: /home/pausa/git-repo
              type: Directory
          - name: src-castle
            hostPath:
              path: /home/pausa/media/shows_ita/castle
              type: Directory
          - name: src-criminal
            hostPath:
              path: "/home/pausa/media/shows_ita/Criminal Minds"
              type: Directory
          - name: src-ranma
            hostPath:
              path: /home/pausa/media/shows_ita/Ranma
              type: Directory
          - name: src-sync
            hostPath:
              path: /home/pausa/media/sync
              type: Directory
          - name: src-db
            hostPath:
              path: /home/pausa/media/db
              type: Directory
          - name: src-dot-config
            hostPath:
              path: /home/pausa/.config
              type: Directory
          - name: dst
            hostPath:
              path: /media/sde1
              type: Directory
          - name: localtime
            hostPath:
              path: /etc/localtime
              type: File
